declare module 'jsonwebtoken';
declare module 'bcrypt';
declare module 'nodemailer';
declare module 'node-cron'
declare module 'express-rate-limit'
declare module 'speakeasy'
declare module 'winston'
declare module 'qrcode'
declare module 'json2csv'